/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Clases.Main;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author fallaa8
 */
public class AnimalesDisponibles extends javax.swing.JFrame {

    /**
     * Creates new form AnimalesDisponibles
     */
    public AnimalesDisponibles() {
        initComponents();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {

                Main.animales.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnBurros = new javax.swing.JButton();
        btnVacas = new javax.swing.JButton();
        btnCaballos = new javax.swing.JButton();
        btnCerdos = new javax.swing.JButton();
        btnAves = new javax.swing.JButton();
        btnCabras = new javax.swing.JButton();
        btnOvejas = new javax.swing.JButton();
        btnConejos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(1400, 1024));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(89, 86, 45));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MENÚ ANIMALES");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 140));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnBurros.setForeground(new java.awt.Color(255, 255, 255));
        btnBurros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pexels-vivian-venhasque-19096301.jpg"))); // NOI18N
        btnBurros.setText("VACAS");
        btnBurros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BURROS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        btnBurros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBurrosActionPerformed(evt);
            }
        });

        btnVacas.setForeground(new java.awt.Color(255, 255, 255));
        btnVacas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vacas.jpg"))); // NOI18N
        btnVacas.setText("VACAS");
        btnVacas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VACAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        btnVacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacasActionPerformed(evt);
            }
        });

        btnCaballos.setForeground(new java.awt.Color(255, 255, 255));
        btnCaballos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pexels-vivian-venhasque-19096301.jpg"))); // NOI18N
        btnCaballos.setText("VACAS");
        btnCaballos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CABALLOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        btnCaballos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaballosActionPerformed(evt);
            }
        });

        btnCerdos.setForeground(new java.awt.Color(255, 255, 255));
        btnCerdos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pexels-vivian-venhasque-19096301.jpg"))); // NOI18N
        btnCerdos.setText("VACAS");
        btnCerdos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CERDOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        btnCerdos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerdosActionPerformed(evt);
            }
        });

        btnAves.setForeground(new java.awt.Color(255, 255, 255));
        btnAves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vacas.jpg"))); // NOI18N
        btnAves.setText("VACAS");
        btnAves.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AVES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        btnAves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvesActionPerformed(evt);
            }
        });

        btnCabras.setForeground(new java.awt.Color(255, 255, 255));
        btnCabras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vacas.jpg"))); // NOI18N
        btnCabras.setText("VACAS");
        btnCabras.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CABRAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        btnCabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCabrasActionPerformed(evt);
            }
        });

        btnOvejas.setForeground(new java.awt.Color(255, 255, 255));
        btnOvejas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vacas.jpg"))); // NOI18N
        btnOvejas.setText("VACAS");
        btnOvejas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OVEJAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        btnOvejas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOvejasActionPerformed(evt);
            }
        });

        btnConejos.setForeground(new java.awt.Color(255, 255, 255));
        btnConejos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vacas.jpg"))); // NOI18N
        btnConejos.setText("VACAS");
        btnConejos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONEJOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        btnConejos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConejosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVacas, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAves, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCaballos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBurros, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerdos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCabras, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOvejas, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConejos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBurros, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCaballos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVacas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerdos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAves, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCabras, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOvejas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConejos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 138, 994, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBurrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBurrosActionPerformed
        Burros burros = new Burros();
        burros.setVisible(true);
        burros.setLocationRelativeTo(null);
        Main.animalesDisponibles.setVisible(false);
    }//GEN-LAST:event_btnBurrosActionPerformed

    private void btnVacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacasActionPerformed
        Vacas vacas = new Vacas();
        vacas.setVisible(true);
        vacas.setLocationRelativeTo(null);
        Main.animalesDisponibles.setVisible(false);
    }//GEN-LAST:event_btnVacasActionPerformed

    private void btnCaballosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaballosActionPerformed
        Caballos caballos = new Caballos();
        caballos.setVisible(true);
        caballos.setLocationRelativeTo(null);
        Main.animalesDisponibles.setVisible(false);
    }//GEN-LAST:event_btnCaballosActionPerformed

    private void btnAvesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvesActionPerformed
        Aves aves = new Aves();
        aves.setVisible(true);
        aves.setLocationRelativeTo(null);
        Main.animalesDisponibles.setVisible(false);
    }//GEN-LAST:event_btnAvesActionPerformed

    private void btnCerdosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerdosActionPerformed
        Cerdos cerdos = new Cerdos();
        cerdos.setVisible(true);
        cerdos.setLocationRelativeTo(null);
        Main.animalesDisponibles.setVisible(false);
    }//GEN-LAST:event_btnCerdosActionPerformed

    private void btnCabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCabrasActionPerformed
        Cabras cabras = new Cabras();
        cabras.setVisible(true);
        cabras.setLocationRelativeTo(null);
        Main.animalesDisponibles.setVisible(false);
    }//GEN-LAST:event_btnCabrasActionPerformed

    private void btnOvejasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOvejasActionPerformed
        Ovejas ovejas = new Ovejas();
        ovejas.setVisible(true);
        ovejas.setLocationRelativeTo(null);
        Main.animalesDisponibles.setVisible(false);
    }//GEN-LAST:event_btnOvejasActionPerformed

    private void btnConejosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConejosActionPerformed
        Conejos conejos = new Conejos();
        conejos.setVisible(true);
        conejos.setLocationRelativeTo(null);
        Main.animalesDisponibles.setVisible(false);
    }//GEN-LAST:event_btnConejosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalesDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalesDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalesDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalesDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalesDisponibles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAves;
    private javax.swing.JButton btnBurros;
    private javax.swing.JButton btnCaballos;
    private javax.swing.JButton btnCabras;
    private javax.swing.JButton btnCerdos;
    private javax.swing.JButton btnConejos;
    private javax.swing.JButton btnOvejas;
    private javax.swing.JButton btnVacas;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
