/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Clases.Main;

/**
 *
 * @author fallaa8
 */
public class Padrinos extends javax.swing.JFrame {

    /**
     * Creates new form RegistroUsuarios
     */
    public Padrinos() {
        initComponents();
        setDefaultCloseOperation(MenuPrincipal.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JLabel();
        jbtReportes = new javax.swing.JButton();
        jtxtNumUsuario = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtCargo = new javax.swing.JLabel();
        jBtnCerrarSesion2 = new javax.swing.JButton();
        jbtEliminar = new javax.swing.JButton();
        jbtModificar = new javax.swing.JButton();
        jbtRegistrar = new javax.swing.JButton();
        jtxtCedula = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 1024));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vaquero.png"))); // NOI18N
        jLabel2.setAlignmentX(0.6F);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 60, 70));

        jtxtNombre.setBackground(new java.awt.Color(232, 232, 232));
        jtxtNombre.setAlignmentX(0.6F);
        jtxtNombre.setMaximumSize(new java.awt.Dimension(80, 20));
        jtxtNombre.setMinimumSize(new java.awt.Dimension(80, 20));
        jtxtNombre.setOpaque(true);
        jtxtNombre.setPreferredSize(new java.awt.Dimension(150, 40));
        getContentPane().add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jbtReportes.setBackground(new java.awt.Color(0, 153, 204));
        jbtReportes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtReportes.setForeground(new java.awt.Color(255, 255, 255));
        jbtReportes.setText("REPORTES");
        jbtReportes.setMaximumSize(new java.awt.Dimension(132, 32));
        jbtReportes.setMinimumSize(new java.awt.Dimension(132, 32));
        jbtReportes.setPreferredSize(new java.awt.Dimension(132, 32));
        jbtReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtReportesActionPerformed(evt);
            }
        });
        getContentPane().add(jbtReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, 140, 40));

        jtxtNumUsuario.setBackground(new java.awt.Color(232, 232, 232));
        jtxtNumUsuario.setAlignmentX(0.6F);
        jtxtNumUsuario.setMaximumSize(new java.awt.Dimension(80, 20));
        jtxtNumUsuario.setMinimumSize(new java.awt.Dimension(80, 20));
        jtxtNumUsuario.setOpaque(true);
        jtxtNumUsuario.setPreferredSize(new java.awt.Dimension(150, 40));
        getContentPane().add(jtxtNumUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("LIBRES Y AMADOS");
        jLabel10.setAlignmentX(0.6F);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 220, -1));

        jtxtCargo.setBackground(new java.awt.Color(232, 232, 232));
        jtxtCargo.setAlignmentX(0.6F);
        jtxtCargo.setMaximumSize(new java.awt.Dimension(80, 20));
        jtxtCargo.setMinimumSize(new java.awt.Dimension(80, 20));
        jtxtCargo.setOpaque(true);
        jtxtCargo.setPreferredSize(new java.awt.Dimension(150, 40));
        getContentPane().add(jtxtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jBtnCerrarSesion2.setText("Cerrar Sesión");
        jBtnCerrarSesion2.setAlignmentX(0.6F);
        jBtnCerrarSesion2.setPreferredSize(new java.awt.Dimension(90, 20));
        jBtnCerrarSesion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCerrarSesion2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCerrarSesion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 120, 30));

        jbtEliminar.setBackground(new java.awt.Color(204, 0, 51));
        jbtEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtEliminar.setText("ELIMINAR");
        jbtEliminar.setPreferredSize(new java.awt.Dimension(132, 32));
        jbtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 590, 140, 40));

        jbtModificar.setBackground(new java.awt.Color(204, 153, 0));
        jbtModificar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtModificar.setForeground(new java.awt.Color(255, 255, 255));
        jbtModificar.setText("MODIFICAR");
        jbtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 140, 40));

        jbtRegistrar.setBackground(new java.awt.Color(51, 153, 0));
        jbtRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jbtRegistrar.setText("REGISTRAR");
        jbtRegistrar.setPreferredSize(new java.awt.Dimension(132, 32));
        jbtRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 140, 40));

        jtxtCedula.setBackground(new java.awt.Color(232, 232, 232));
        jtxtCedula.setAlignmentX(0.6F);
        jtxtCedula.setMaximumSize(new java.awt.Dimension(80, 20));
        jtxtCedula.setMinimumSize(new java.awt.Dimension(80, 20));
        jtxtCedula.setOpaque(true);
        jtxtCedula.setPreferredSize(new java.awt.Dimension(150, 40));
        getContentPane().add(jtxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 51, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Menú Padrinos");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 880, 140));

        jLabel9.setBackground(new java.awt.Color(252, 252, 252));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        jLabel9.setToolTipText("");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 180, 200));

        jLabel13.setBackground(new java.awt.Color(252, 252, 252));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton-eliminar.png"))); // NOI18N
        jLabel13.setToolTipText("");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 180, 200));

        jLabel14.setBackground(new java.awt.Color(252, 252, 252));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte-de-negocios.png"))); // NOI18N
        jLabel14.setToolTipText("");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel14.setOpaque(true);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 180, 200));

        jLabel15.setBackground(new java.awt.Color(252, 252, 252));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registro-en-linea.png"))); // NOI18N
        jLabel15.setToolTipText("");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 180, 200));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 880, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRegistrarActionPerformed
        Main.registroPadrino.setVisible(true);
        Main.registroPadrino.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbtRegistrarActionPerformed

    private void jbtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtModificarActionPerformed
        Main.modificarPadrino.setVisible(true);
        Main.modificarPadrino.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbtModificarActionPerformed

    private void jbtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEliminarActionPerformed
       Main.eliminarPadrino.setVisible(true);
       Main.eliminarPadrino.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbtEliminarActionPerformed

    private void jbtReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtReportesActionPerformed
      Main.reportesPadrinos.setVisible(true);
      Main.reportesPadrinos.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbtReportesActionPerformed

    private void jBtnCerrarSesion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCerrarSesion2ActionPerformed
       Main.iniciar.setVisible(true);
       Main.iniciar.setLocationRelativeTo(null);
       Main.padrino.setVisible(false);
    }//GEN-LAST:event_jBtnCerrarSesion2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Padrinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Padrinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Padrinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Padrinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Padrinos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCerrarSesion2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtEliminar;
    private javax.swing.JButton jbtModificar;
    private javax.swing.JButton jbtRegistrar;
    private javax.swing.JButton jbtReportes;
    private javax.swing.JLabel jtxtCargo;
    private javax.swing.JLabel jtxtCedula;
    private javax.swing.JLabel jtxtNombre;
    private javax.swing.JLabel jtxtNumUsuario;
    // End of variables declaration//GEN-END:variables
}
